### ISSUE TITLE
Multus IPvlan , secondary IP addresses 

### ISSUE THREAD

**Issue by elgamal2020** [aws-samples/eks-install-guide-for-multus#1]
Hello , 
Referring to the blog article https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-multus-cni/

I have tried the network attachment definitions you demonstrated and it is not working unless I assign the pod secondary IP  "10.0.4.70" in the example you provided as a secondary IP on the network interface which will be problematic as we need to have the pod moving between nodes without needing to inform the EC2 instances of each IP address multus use with IPVLAN 

[
![secondary ip](https://user-images.githubusercontent.com/56054199/128443301-07e3ebb5-9e2e-4919-bde3-4f0ab77789f3.png)
](url)

**Comment by agr-priyanshu** [comment]
I tried the same combination but it is not working even after adding the secondary IP in multus ENI. Does it require any update after adding the secondary IP? Can we add all IPs in advance as secondary IP like it is already done for VPC CNI? 

Apparently the example provided in blog seems incomplete as the image lists out another app sampleapp-2 which is expected to be on a different node.

Also does this setup support worker nodes across AZs? In all the setup the cluster was created as multi AZ but the worker nodes are kept in a single AZ only?

**Comment by sheetaljoshi** [comment]
@elgamal2020 , thanks for reporting the issue, this is a known experience gap. We are working on it internally, we will update the issue when we have more details to share.

**Comment by sheetaljoshi** [comment]
@agr-priyanshu. Thanks for opening this issue and bringing it to our notice about sample-app2. The sample-app2 is just for illustration purpose. The examples used are very simple with host-local ipam plugin. We have customers using [whereabouts](https://github.com/k8snetworkplumbingwg/whereabouts) IPAM plugin for multi node deployments. We are working on the ENI and secondary IP mapping requirement. We will update the issue when we have more details to share.

**Comment by elgamal2020** [comment]
Could you please confirm also how to generate the AWS_SESSION_TOKEN ?
Thanks a lot

**Comment by elgamal2020** [comment]
@sheetaljoshi

Could you please tell us how further the ips for the network attachement can be assoicated with elastic ip adresses ?

Thanks a lot
Best Regards
