### ISSUE TITLE
Cloud formation script nodegroup bug

### ISSUE THREAD

**Issue by Lautreck** [aws-samples/eks-install-guide-for-multus#14]
Hello, 
i'd like to report a bug or a error in the nodegroup script.
when selecting the subnets, it's not explicit that we have to pick them in the right order.
i thought the script would obviously put the lower one 10.0.4.0 on the first ENI and the higher one 10.0.6.0 on the second ENI, and go on like that for more and more subnets if we add more.

unfortunatly its first picked first introduced in the ENI, which is very easy to make mistakes with.

Cheers

**Comment by raghs-aws** [comment]
I will add it in the documentation, mentioning @Lautreck .  Subnets are taken in the same order , It wouldn't be correct for the cloudformation to override the provided order, as some users might want to keep 10.0.6.0 as eth1 and 10.0.5.0 as eth2.
