### ISSUE TITLE
Upgrade nodegroup k8s version to 1.26 from 1.21

### ISSUE THREAD

**Issue by TheRushingWookie** [aws-samples/eks-install-guide-for-multus#24]
Currently node groups creating using the nodegroup yaml file are broken as they provision nodes with an AMI for K8S 1.21. I changed the image id from
```/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id```
to
```/aws/service/eks/optimized-ami/1.26/amazon-linux-2/recommended/image_id```
and it fixed the nodegroup creation

**Comment by raghs-aws** [comment]
This value is configurable in the Cloud formation template. You can change it during filling the value.  Since users can use any EKS version, this value is configurable and for simplicity a default value is given. One can change 1.21 to 1.26 
  NodeImageIdSSMParam:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id

**Comment by raghs-aws** [comment]
I am closing it as its not a bug. Please let me know if you think there are more issues
