### ISSUE TITLE
macvlan support

### ISSUE THREAD

**Issue by jk1333** [aws-samples/eks-install-guide-for-multus#3]
Hello, thanks for multus support in eks,
I have one query regarding macvlan support.
There are many requirements to fix mac address to PODs for legacy applications
(These are license programs which runs on specific mac address)

From search, we found 
1. use NET_ADMIN which needs more privilege not preferable
2. macvlan on multus

So I'd like to know I can run following sample.
https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/examples/macvlan-pod.yml
I'm trying to test but it takes time :(

**Comment by raghs-aws** [comment]
Hi Macvlan would not work across the node as VPC supports Layer 3 networking. Please use IPVLAN CNI.
