### ISSUE TITLE
lambda function

### ISSUE THREAD

**Issue by elgamal2020** [aws-samples/eks-install-guide-for-multus#5]
Hello,

I have problems with Lambda function , the full description is attached 

Following the link :
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-multus-cni/

The role of the  should be adding automatically the IP for the secondary network attachment 

It is not working, the example shown is using a cluster of 1 node where it be working regardless of secondary network attachments 

I have tried with both the default AMI image and ubuntu 20.04 based 

[Multus_problem.docx](https://github.com/aws-samples/eks-install-guide-for-multus/files/7568452/Multus_problem.docx)

Thanks a lot
Best Regards

**Comment by raghs-aws** [comment]
Multus pods need the secondary IPs to communicate. Please refer to
https://github.com/aws-samples/eks-automated-ipmgmt-multus-pods
