### ISSUE TITLE
unable to ssh to worker nodes from bastion instance

### ISSUE THREAD

**Issue by kaitaklam** [aws-samples/eks-install-guide-for-multus#6]
once on bastion instance. I try to ssh to worker node instances, using private workernode IP address.
But I can't login to the workernodes.

**Comment by Lautreck** [comment]
use k9s and this  https://github.com/kvaps/kubectl-node-shell

with k9s you will have a graphic interface to select the nodes, and with this extension you will be able to go directly in the node shell and work on it.

it work like a charm

**Comment by raghs-aws** [comment]
@kaitaklam you would need to open the inbound port/IPs for the bastion nodes.
